-- ============================================================================
-- BANCO DE DADOS DO PAINEL  ·  Giovanna Carrilho
-- ============================================================================
--
-- ONDE COLAR ESTE ARQUIVO:
--   1. Entre em https://supabase.com e abra o seu projeto
--   2. No menu da esquerda, clique em "SQL Editor"
--   3. Clique em "New query"
--   4. Copie TODO o conteudo deste arquivo e cole na caixa
--   5. Clique no botao verde "Run" (ou aperte Ctrl+Enter)
--   6. Tem que aparecer "Success. No rows returned"
--
-- Este arquivo pode ser rodado mais de uma vez sem quebrar nada.
-- Ele nao apaga os seus dados, so conserta a estrutura e as regras.
--
-- ATENCAO: este arquivo cria so a ESTRUTURA, sem nenhum dado seu.
-- Os seus dados vindos do Notion estao no arquivo migracao-notion.sql,
-- que voce recebeu separado e que NAO esta no GitHub, porque contem
-- CPF, endereco e anotacoes sobre pessoas reais.
--
-- ============================================================================


-- ============================================================================
-- BLOCO 1  ·  MEU NEGOCIO
-- ============================================================================

-- O seu Pipeline de Leads, que alimenta a aba Pipeline.
create table if not exists public.leads (
  id              bigint generated by default as identity primary key,
  lead            text not null default '',
  tipo            text not null default 'Corretora',
  -- Corretora (Leitura de Marca) ou Empresa (palestra). Sao dois comerciais
  -- diferentes: corretora e conversa individual, empresa e proposta B2B.
  contato         text default '',            -- Instagram ou WhatsApp
  pessoa          text default '',            -- so Empresa: quem fala, e o cargo
  email           text default '',            -- so Empresa: para onde vai a proposta
  status          text not null default 'Contato realizado',
  -- Contato realizado, Conversa, Intencao, Oportunidade, Oferta/Follow-up, Cliente, Nao agora
  icp             text default 'A confirmar', -- Sim, Fora do ICP, A confirmar
  origem          text default '',
  -- Instagram, Grupo WhatsApp, ManyChat, Indicacao, Comentario, Palestra, Circulo pessoal, Base antiga
  tempo_mercado   text default '',
  primeiro_contato date,             -- quando essa conversa comecou
  ultimo_contato  date,
  respondeu       boolean not null default false,
  oferta          text default '',
  -- Leitura de Marca, Programa de Ativacao, Raio-X de Marca, Palestra.
  -- A mesma pessoa pode ter duas conversas, uma por oferta.
  atualizado_em   timestamptz not null default now(),
  -- carimbado sozinho pelo banco a cada alteracao. Nao e "ultimo contato":
  -- ultimo contato e o dia da conversa, este e o dia em que a ficha mudou.
  -- marcado: ela falou e a bola esta com voce. E o que sobe para o topo
  -- da tela Hoje, com etiqueta laranja.
  proximo_passo   text default '',            -- acao concreta e unica
  frase_real      text default '',            -- a fala da propria pessoa
  portoes         text[] not null default '{}',
  -- os 4 movimentos que acontecem DENTRO de Intencao, na ordem:
  -- Microdiagnostico, Prova especifica, Levantada de mao, Confirmacao de entendimento.
  -- So depois dos quatro a lead sobe para Oportunidade.
  notas           text default '',
  criado_em       timestamptz not null default now()
);

-- A sua Base de Clientes, que alimenta a aba Clientes.
-- Guarda tambem os dados fiscais que voce usa para emitir nota.
create table if not exists public.clientes (
  id                bigint generated by default as identity primary key,
  cliente           text not null default '',
  lead_id           bigint,                   -- de qual lead do pipeline esta cliente veio
  historico         text default '',          -- a historia da venda, que no Notion esta no campo Lead
  crm_status        text[] not null default '{}',
  -- pode ter mais de um: Lead, Desqualificado, Forms preenchido, Call 1 agendada,
  -- Enviar material etapa 1, Call 2 agendada, Enviar material etapa 2,
  -- Em negociacao, Aguardando pagamento, Pago, Concluido
  objetivo_contato  text default '',
  -- Depoimento, Negociacao, Entrega de material, Agendamento, Sessao agendada,
  -- Oferta Upgrade
  proximo_contato   date,
  origem            text default '',
  produto           text default 'Leitura de Marca',
  -- Leitura de Marca, Mentoria, Palestra, Workshop, Outro
  atualizado_em     timestamptz not null default now(),
  -- carimbado sozinho pelo banco a cada alteracao
  valor             numeric(12,2) not null default 0,
  -- o valor cheio que a cliente pagou, com juros de parcelamento se houver
  valor_liquido     numeric(12,2) not null default 0,
  -- o que entrou de verdade na conta, ja sem as taxas da plataforma.
  -- Em zero, o painel considera que entrou o valor cheio.
  data_pagamento    date,
  forma_pagamento   text default '',          -- PIX, Cartao Parcelado, Cartao a vista, Boleto
  status_nf         text default 'A emitir',  -- A emitir, Emitida
  num_nota          text default '',
  -- --- dados fiscais, so aparecem quando voce abre a ficha do cliente ---
  cpf_cnpj          text default '',
  endereco          text default '',
  cep               text default '',
  cidade_uf         text default '',
  email             text default '',
  telefone          text default '',
  criado_em         timestamptz not null default now()
);


-- ============================================================================
-- BLOCO 2  ·  CONSERTOS PARA QUEM JA RODOU UMA VERSAO ANTIGA
-- ============================================================================
-- Se alguma tabela ja existia sem um campo, estas linhas acrescentam o que falta.
-- Se estiver tudo certo, elas nao fazem nada. Pode deixar.

alter table public.leads     add column if not exists notas     text default '';
alter table public.leads     add column if not exists portoes   text[] not null default '{}';
alter table public.leads     add column if not exists primeiro_contato date;
alter table public.leads     add column if not exists tipo      text not null default 'Corretora';
alter table public.leads     add column if not exists pessoa    text default '';
alter table public.leads     add column if not exists email     text default '';
alter table public.leads     add column if not exists respondeu boolean not null default false;
alter table public.leads     add column if not exists oferta    text default '';
alter table public.leads     add column if not exists atualizado_em timestamptz not null default now();
alter table public.clientes  add column if not exists atualizado_em timestamptz not null default now();
alter table public.clientes  add column if not exists lead_id   bigint;
alter table public.clientes  add column if not exists historico text default '';
alter table public.clientes  add column if not exists crm_status text[] not null default '{}';
alter table public.clientes  add column if not exists valor_liquido numeric(12,2) not null default 0;


-- ============================================================================
-- BLOCO 3  ·  INDICES, PARA O PAINEL ABRIR RAPIDO
-- ============================================================================

create index if not exists leads_status_idx       on public.leads (status);
create index if not exists leads_tipo_idx         on public.leads (tipo);
create index if not exists leads_ultimo_idx       on public.leads (ultimo_contato);
create index if not exists clientes_proximo_idx   on public.clientes (proximo_contato);
create index if not exists clientes_lead_idx      on public.clientes (lead_id);
create index if not exists clientes_pagamento_idx on public.clientes (data_pagamento);


-- ============================================================================
-- BLOCO 3.1  ·  O CARIMBO DE ATUALIZACAO
-- ============================================================================
-- Toda vez que uma linha muda, o banco carimba a hora sozinho em
-- atualizado_em. Assim a data nunca depende de alguem lembrar de preencher.

create or replace function public.carimbar_atualizacao()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.atualizado_em := now();
  return new;
end;
$$;

drop trigger if exists carimbo_leads    on public.leads;
drop trigger if exists carimbo_clientes on public.clientes;

create trigger carimbo_leads
  before update on public.leads
  for each row execute function public.carimbar_atualizacao();

create trigger carimbo_clientes
  before update on public.clientes
  for each row execute function public.carimbar_atualizacao();


-- ============================================================================
-- BLOCO 4  ·  A TRANCA  (RLS, Row Level Security)
-- ============================================================================
-- Esta e a parte mais importante do arquivo. NAO APAGUE.
--
-- Ligar o RLS numa tabela significa: por padrao, NINGUEM pode fazer nada.
-- Depois disso, so passa quem tiver uma permissao escrita explicitamente.
-- Como a chave publica do seu site fica visivel para qualquer pessoa,
-- e o RLS que impede um estranho de ler a sua base de clientes,
-- com CPF, endereco e telefone, e as suas anotacoes sobre cada lead.

alter table public.leads    enable row level security;
alter table public.clientes enable row level security;

-- Garantia extra: nem o dono da tabela escapa da tranca.
alter table public.leads    force row level security;
alter table public.clientes force row level security;


-- ============================================================================
-- BLOCO 5  ·  AS PERMISSOES
-- ============================================================================
-- Primeiro a gente apaga qualquer permissao antiga com o mesmo nome,
-- para este arquivo poder ser rodado mais de uma vez sem dar erro.

drop policy if exists "logada faz tudo em leads"         on public.leads;
drop policy if exists "logada faz tudo em clientes"      on public.clientes;
drop policy if exists "visitante pode virar lead"        on public.leads;

-- ----------------------------------------------------------------------------
-- 5.1  Voce, logada, faz tudo em todas as tabelas
-- ----------------------------------------------------------------------------
-- "to authenticated" quer dizer: so vale para quem entrou com e-mail e senha.
-- Quem nao esta logado nao aparece aqui, ou seja: nao le e nao escreve nada.
--
-- ATENCAO, um passo seu no painel do Supabase:
-- va em Authentication, depois Sign In / Providers, e DESLIGUE
-- "Allow new users to sign up". Sem isso, um estranho poderia criar uma
-- conta no seu projeto e essa conta passaria por estas permissoes.
-- Com a criacao de conta desligada, a unica usuaria logada possivel e voce.

create policy "logada faz tudo em leads" on public.leads
  for all to authenticated using (true) with check (true);

create policy "logada faz tudo em clientes" on public.clientes
  for all to authenticated using (true) with check (true);

-- ----------------------------------------------------------------------------
-- 5.2  A UNICA EXCECAO  ·  qualquer pessoa pode se cadastrar como lead novo
-- ----------------------------------------------------------------------------
-- Serve para o dia em que voce colocar um formulario no site.
-- E so INSERT, nunca SELECT: um visitante consegue deixar o contato dele,
-- e nao consegue ler nem uma linha do seu pipeline.
-- O "with check" obriga o status a entrar no comeco do funil.

create policy "visitante pode virar lead" on public.leads
  for insert to anon
  with check (status = 'Contato realizado');

-- Nao existe mais nenhuma outra excecao. Em clientes,
-- quem nao esta logado nao faz absolutamente nada.


-- ============================================================================
-- FIM. Se apareceu "Success", a estrutura esta pronta: duas tabelas,
-- leads e clientes, as duas trancadas pelo RLS.
-- ============================================================================
