-- ============================================================================
-- BANCO DE DADOS DO PAINEL  ·  Giovanna Carrilho
-- ============================================================================
--
-- ONDE COLAR ESTE ARQUIVO:
--   1. Entre em https://supabase.com e abra o seu projeto
--   2. No menu da esquerda, clique em "SQL Editor"
--   3. Clique em "New query"
--   4. Copie TODO o conteudo deste arquivo e cole na caixa
--   5. Clique no botao verde "Run" (ou aperte Ctrl+Enter)
--   6. Tem que aparecer "Success. No rows returned"
--
-- Este arquivo pode ser rodado mais de uma vez sem quebrar nada.
-- Ele nao apaga os seus dados, so conserta a estrutura e as regras.
--
-- ATENCAO: este arquivo cria so a ESTRUTURA, sem nenhum dado seu.
-- Os seus dados vindos do Notion estao no arquivo migracao-notion.sql,
-- que voce recebeu separado e que NAO esta no GitHub, porque contem
-- CPF, endereco e anotacoes sobre pessoas reais.
--
-- ============================================================================


-- ============================================================================
-- BLOCO 1  ·  MEU CONTEUDO
-- ============================================================================

-- O seu Banco de Pautas, que alimenta a aba Pautas e o Calendario.
-- Os nomes dos campos sao os mesmos que voce ja usa no Notion.
create table if not exists public.pautas (
  id                 bigint generated by default as identity primary key,
  pauta              text not null default '',
  data               date,                       -- quando vai ao ar
  status             text not null default 'Ideia',
  -- Pesquisa, Ideia, Desenvolvendo, Pronto, Publicado
  formato            text default 'A definir',
  -- Reel analise, Reel falado, Reel cena, Carrossel, Estatico, POV, Stories, Grupo Whatsapp
  formato_editorial  text default '',
  -- Analises, Minha Historia, Educativos, Frases de Impacto
  macrotema          text default '',
  -- Reconhecimento, Comunicacao, Mercado Imobiliario, Essencia, Vida Real
  objetivo           text[] not null default '{}',
  -- pode ter mais de um: Alcance, Autoridade, Conexao, Conversao, Sustentacao
  publicado          boolean not null default false,
  notas              text default '',
  criado_em          timestamptz not null default now()
);


-- ============================================================================
-- BLOCO 2  ·  MEU NEGOCIO
-- ============================================================================

-- O seu Pipeline de Leads, que alimenta a aba Pipeline.
create table if not exists public.leads (
  id              bigint generated by default as identity primary key,
  lead            text not null default '',
  contato         text default '',            -- Instagram ou WhatsApp
  status          text not null default 'Contato realizado',
  -- Contato realizado, Conversa, Intencao, Oportunidade, Oferta/Follow-up, Cliente, Nao agora
  icp             text default 'A confirmar', -- Sim, Fora do ICP, A confirmar
  origem          text default '',
  -- Instagram, Grupo WhatsApp, ManyChat, Indicacao, Comentario, Palestra, Circulo pessoal, Base antiga
  tempo_mercado   text default '',
  ultimo_contato  date,
  proximo_passo   text default '',            -- acao concreta e unica
  frase_real      text default '',            -- a fala da propria pessoa
  notas           text default '',
  criado_em       timestamptz not null default now()
);

-- A sua Base de Clientes, que alimenta a aba Clientes.
-- Guarda tambem os dados fiscais que voce usa para emitir nota.
create table if not exists public.clientes (
  id                bigint generated by default as identity primary key,
  cliente           text not null default '',
  historico         text default '',          -- a historia da venda, que no Notion esta no campo Lead
  crm_status        text[] not null default '{}',
  -- pode ter mais de um: Lead, Desqualificado, Forms preenchido, Call 1 agendada,
  -- Enviar material etapa 1, Call 2 agendada, Enviar material etapa 2,
  -- Em negociacao, Aguardando pagamento, Pago, Concluido
  objetivo_contato  text default '',
  -- Depoimento, Negociacao, Entrega de material, Agendamento, Sessao agendada
  proximo_contato   date,
  origem            text default '',
  produto           text default 'Leitura de Marca',
  -- Leitura de Marca, Mentoria, Palestra, Workshop, Outro
  valor             numeric(12,2) not null default 0,
  data_pagamento    date,
  forma_pagamento   text default '',          -- PIX, Cartao Parcelado, Cartao a vista, Boleto
  status_nf         text default 'A emitir',  -- A emitir, Emitida
  num_nota          text default '',
  -- --- dados fiscais, so aparecem quando voce abre a ficha do cliente ---
  cpf_cnpj          text default '',
  endereco          text default '',
  cep               text default '',
  cidade_uf         text default '',
  email             text default '',
  telefone          text default '',
  criado_em         timestamptz not null default now()
);


-- ============================================================================
-- BLOCO 3  ·  MEU SITE
-- ============================================================================

-- Os videos que podem aparecer no seu site, na aba Portfolio.
create table if not exists public.videos (
  id          bigint generated by default as identity primary key,
  titulo      text not null default '',
  link        text not null default '',
  nicho       text default '',
  formato     text default '',
  marca       text default '',
  destaque    text default '',
  ordem       integer not null default 0,
  visivel     boolean not null default true,
  criado_em   timestamptz not null default now()
);

-- O registro de quem visitou o seu site. Comeca vazia de proposito.
create table if not exists public.visitas (
  id          bigint generated by default as identity primary key,
  data        date not null default current_date,
  pagina      text default '/',
  origem      text default 'direto',
  criado_em   timestamptz not null default now()
);


-- ============================================================================
-- BLOCO 4  ·  CONSERTOS PARA QUEM JA RODOU UMA VERSAO ANTIGA
-- ============================================================================
-- Se alguma tabela ja existia sem um campo, estas linhas acrescentam o que falta.
-- Se estiver tudo certo, elas nao fazem nada. Pode deixar.

alter table public.pautas    add column if not exists notas     text default '';
alter table public.pautas    add column if not exists objetivo  text[] not null default '{}';
alter table public.leads     add column if not exists notas     text default '';
alter table public.clientes  add column if not exists historico text default '';
alter table public.clientes  add column if not exists crm_status text[] not null default '{}';
alter table public.videos    add column if not exists destaque  text default '';
alter table public.visitas   add column if not exists origem    text default 'direto';


-- ============================================================================
-- BLOCO 5  ·  INDICES, PARA O PAINEL ABRIR RAPIDO
-- ============================================================================

create index if not exists pautas_data_idx        on public.pautas (data);
create index if not exists pautas_status_idx      on public.pautas (status);
create index if not exists leads_status_idx       on public.leads (status);
create index if not exists leads_ultimo_idx       on public.leads (ultimo_contato);
create index if not exists clientes_proximo_idx   on public.clientes (proximo_contato);
create index if not exists clientes_pagamento_idx on public.clientes (data_pagamento);
create index if not exists videos_ordem_idx       on public.videos (ordem);
create index if not exists visitas_data_idx       on public.visitas (data);


-- ============================================================================
-- BLOCO 6  ·  A TRANCA  (RLS, Row Level Security)
-- ============================================================================
-- Esta e a parte mais importante do arquivo. NAO APAGUE.
--
-- Ligar o RLS numa tabela significa: por padrao, NINGUEM pode fazer nada.
-- Depois disso, so passa quem tiver uma permissao escrita explicitamente.
-- Como a chave publica do seu site fica visivel para qualquer pessoa,
-- e o RLS que impede um estranho de ler a sua base de clientes,
-- com CPF, endereco e telefone, e as suas anotacoes sobre cada lead.

alter table public.pautas   enable row level security;
alter table public.leads    enable row level security;
alter table public.clientes enable row level security;
alter table public.videos   enable row level security;
alter table public.visitas  enable row level security;

-- Garantia extra: nem o dono da tabela escapa da tranca.
alter table public.pautas   force row level security;
alter table public.leads    force row level security;
alter table public.clientes force row level security;
alter table public.videos   force row level security;
alter table public.visitas  force row level security;


-- ============================================================================
-- BLOCO 7  ·  AS PERMISSOES
-- ============================================================================
-- Primeiro a gente apaga qualquer permissao antiga com o mesmo nome,
-- para este arquivo poder ser rodado mais de uma vez sem dar erro.

drop policy if exists "logada faz tudo em pautas"        on public.pautas;
drop policy if exists "logada faz tudo em leads"         on public.leads;
drop policy if exists "logada faz tudo em clientes"      on public.clientes;
drop policy if exists "logada faz tudo em videos"        on public.videos;
drop policy if exists "logada faz tudo em visitas"       on public.visitas;
drop policy if exists "visitante pode virar lead"        on public.leads;
drop policy if exists "visitante pode registrar visita"  on public.visitas;

-- ----------------------------------------------------------------------------
-- 7.1  Voce, logada, faz tudo em todas as tabelas
-- ----------------------------------------------------------------------------
-- "to authenticated" quer dizer: so vale para quem entrou com e-mail e senha.
-- Quem nao esta logado nao aparece aqui, ou seja: nao le e nao escreve nada.
--
-- ATENCAO, um passo seu no painel do Supabase:
-- va em Authentication, depois Sign In / Providers, e DESLIGUE
-- "Allow new users to sign up". Sem isso, um estranho poderia criar uma
-- conta no seu projeto e essa conta passaria por estas permissoes.
-- Com a criacao de conta desligada, a unica usuaria logada possivel e voce.

create policy "logada faz tudo em pautas" on public.pautas
  for all to authenticated using (true) with check (true);

create policy "logada faz tudo em leads" on public.leads
  for all to authenticated using (true) with check (true);

create policy "logada faz tudo em clientes" on public.clientes
  for all to authenticated using (true) with check (true);

create policy "logada faz tudo em videos" on public.videos
  for all to authenticated using (true) with check (true);

create policy "logada faz tudo em visitas" on public.visitas
  for all to authenticated using (true) with check (true);

-- ----------------------------------------------------------------------------
-- 7.2  PRIMEIRA EXCECAO  ·  qualquer pessoa pode se cadastrar como lead novo
-- ----------------------------------------------------------------------------
-- Serve para o dia em que voce colocar um formulario no site.
-- E so INSERT, nunca SELECT: um visitante consegue deixar o contato dele,
-- e nao consegue ler nem uma linha do seu pipeline.
-- O "with check" obriga o status a entrar no comeco do funil.

create policy "visitante pode virar lead" on public.leads
  for insert to anon
  with check (status = 'Contato realizado');

-- ----------------------------------------------------------------------------
-- 7.3  SEGUNDA EXCECAO  ·  qualquer pessoa pode registrar uma visita
-- ----------------------------------------------------------------------------
-- Tambem so INSERT. O visitante grava que passou por ali,
-- e nao consegue ver quantas visitas voce teve. Ler, so voce.

create policy "visitante pode registrar visita" on public.visitas
  for insert to anon
  with check (true);

-- Nao existe mais nenhuma outra excecao. Em pautas, clientes e videos,
-- quem nao esta logado nao faz absolutamente nada.


-- ============================================================================
-- BLOCO 8  ·  UMA LINHA DE EXEMPLO EM VIDEOS
-- ============================================================================
-- So em videos, porque as outras tabelas recebem os seus dados de verdade
-- pelo arquivo migracao-notion.sql.
-- A tabela visitas NAO recebe exemplo: os seus numeros comecam em zero.

insert into public.videos (titulo, link, nicho, formato, marca, destaque, ordem, visivel)
select 'EXEMPLO, pode apagar esta linha',
       'https://www.instagram.com/reel/exemplo/',
       'Marca pessoal', 'Reel analise', 'Leitura de Marca',
       '2,4M views', 1, false
where not exists (select 1 from public.videos);


-- ============================================================================
-- BLOCO 9  ·  OPCIONAL, LIMPEZA DAS TABELAS ANTIGAS
-- ============================================================================
-- As tabelas abaixo eram do painel antigo, de creator UGC. O painel novo
-- nao usa nenhuma delas. Elas nao atrapalham em nada se ficarem ali.
--
-- Se voce quiser apagar de vez, TIRE OS DOIS TRACOS do comeco das 4 linhas
-- abaixo e rode este arquivo de novo. Isso apaga as tabelas e tudo que
-- estiver dentro delas, e nao tem como voltar atras.

-- drop table if exists public.marcas;
-- drop table if exists public.campanhas;
-- drop table if exists public.calendario;
-- drop table if exists public.marcados;


-- ============================================================================
-- FIM. Se apareceu "Success", a estrutura esta pronta.
-- Agora rode o arquivo migracao-notion.sql para trazer os seus dados.
-- ============================================================================
